name: Check Spelling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "18"
      - run: npm install -g cspell
      - run: cspell --config ./cSpell.json "**/*.md
